server:
  port: 8888

spring:
  data:
    mongodb:
      database: inbobwetrust
      uri: mongodb://localhost:27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

restClient:
  proxy:
    host: http://localhost:8090
    shopUrl: ${restClient.proxy.host}/relay/v1/shop
    agencyUrl: ${restClient.proxy.host}/relay/v1/agency



