name: Relay-service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        TEST_COMMAND: [ '--info delivery-relay-service:integrationTest', '--info delivery-relay-service:test', '--info :delivery-relay-service:generateJacocoTestCoverage' ]

    steps:
      - uses: actions/checkout@v2

      - name: AWS > Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew ${{ matrix.TEST_COMMAND }}

  aws_update_ecs:
    runs-on: ubuntu-latest
    steps:
      - name: SSH > git checkout > run new
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          host: ${{ secrets.AWS_EC2_RELAY_SERVICE }}
          username: ${{ secrets.AWS_EC2_USER }}
          script: |
            sudo rm -R /home/ec2-user/in-bob-we-trust
            cd /home/ec2-user
            git clone https://github.com/f-lab-edu/in-bob-we-trust
            cd /home/ec2-user/in-bob-we-trust
            git checkout ${{ github.sha }}
            ./gradlew :delivery-relay-service:build -x test -x integrationTest
            echo "running processes 1-----------------------------"
            sudo kill -9 $(lsof -t -i:8888 -sTCP:LISTEN)
            cd /home/ec2-user/in-bob-we-trust
            java -Dspring.data.mongodb.uri="${{ secrets.MONGO_DB_CONN }}" \
            -Dspring.zipkin.base-url="${{ secrets.AWS_ZIPKIN_URL }}" \
            -jar ./delivery-relay-service/build/libs/delivery-relay-service.jar \
            --spring.profiles.active=production > /dev/null 2>&1 & disown
